-- TB_MEMBER 테이블에 누락된 컬럼 추가
-- 실행 전 반드시 백업을 수행하세요!

-- 1. 이메일 주소
ALTER TABLE TB_MEMBER ADD COLUMN EMAIL VARCHAR(100);

-- 2. 회사 전화번호
ALTER TABLE TB_MEMBER ADD COLUMN COMPANY_PHONE VARCHAR(20);

-- 3. 우편번호
ALTER TABLE TB_MEMBER ADD COLUMN POSTCODE VARCHAR(10);

-- 4. 주소
ALTER TABLE TB_MEMBER ADD COLUMN ADDRESS VARCHAR(500);

-- 5. 상세주소
ALTER TABLE TB_MEMBER ADD COLUMN ADDRESS_DETAIL VARCHAR(500);

-- 6. 담당자 휴대전화
ALTER TABLE TB_MEMBER ADD COLUMN MANAGER_MOBILE VARCHAR(20);

-- 7. 담당자 이메일
ALTER TABLE TB_MEMBER ADD COLUMN MANAGER_EMAIL VARCHAR(100);

-- 8. 마케팅 정보 수신 동의 (Y/N)
ALTER TABLE TB_MEMBER ADD COLUMN AGREE_MARKETING CHAR(1) DEFAULT 'N';

-- 9. SMS 수신 동의 (Y/N)
ALTER TABLE TB_MEMBER ADD COLUMN AGREE_SMS CHAR(1) DEFAULT 'N';

-- 완료 후 테이블 구조 확인
-- DESC TB_MEMBER; (MySQL)
-- \d TB_MEMBER (PostgreSQL)
