-- ========================================
-- 판매유형 코드 추가 (007002)
-- 콤보박스 연동을 위해 필요한 코드
-- ========================================

-- 007002 판매유형 코드 추가
INSERT INTO TB_CODE (GROUP_CODE, CODE, CODE_NAME, SORT_ORDER, USE_YN) VALUES
('007', '007002', '판매유형', 2, 'Y')
ON DUPLICATE KEY UPDATE CODE_NAME = VALUES(CODE_NAME), SORT_ORDER = VALUES(SORT_ORDER), USE_YN = VALUES(USE_YN);

-- 007002 상세코드 추가 (원물/가공)
INSERT INTO TB_DETAIL_CODE (GROUP_CODE, CODE, DETAIL_CODE, DETAIL_CODE_NAME, SORT_ORDER, USE_YN) VALUES
('007', '007002', '007002001', '원물', 1, 'Y'),
('007', '007002', '007002002', '가공', 2, 'Y')
ON DUPLICATE KEY UPDATE DETAIL_CODE_NAME = VALUES(DETAIL_CODE_NAME), SORT_ORDER = VALUES(SORT_ORDER), USE_YN = VALUES(USE_YN);

-- 확인 쿼리
SELECT * FROM TB_CODE WHERE GROUP_CODE = '007';
SELECT * FROM TB_DETAIL_CODE WHERE GROUP_CODE = '007';
