-- ========================================
-- TB_MEMBER 테이블에 EMAIL 컬럼 추가
-- ========================================

-- EMAIL 컬럼 추가
ALTER TABLE TB_MEMBER 
ADD COLUMN EMAIL VARCHAR(100) COMMENT '이메일 주소';

-- 인덱스 추가 (검색 성능 향상)
CREATE INDEX IDX_TB_MEMBER_EMAIL ON TB_MEMBER(EMAIL);

-- 확인
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'TB_MEMBER'
  AND COLUMN_NAME = 'EMAIL';
