-- ========================================
-- 코드관리 시스템 데이터베이스 스키마 (MariaDB)
-- ========================================

-- 1. 그룹코드 테이블
CREATE TABLE IF NOT EXISTS TB_GROUP_CODE (
    GROUP_CODE VARCHAR(10) PRIMARY KEY COMMENT '그룹코드',
    GROUP_CODE_NAME VARCHAR(100) NOT NULL COMMENT '그룹코드명',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    MOD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='그룹코드';

-- 2. 코드 테이블
CREATE TABLE IF NOT EXISTS TB_CODE (
    GROUP_CODE VARCHAR(10) COMMENT '그룹코드',
    CODE VARCHAR(10) COMMENT '코드',
    CODE_NAME VARCHAR(100) NOT NULL COMMENT '코드명',
    SORT_ORDER INT DEFAULT 0 COMMENT '정렬순서',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    MOD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (GROUP_CODE, CODE),
    CONSTRAINT FK_CODE_GROUP FOREIGN KEY (GROUP_CODE) 
        REFERENCES TB_GROUP_CODE(GROUP_CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='코드';

-- 3. 상세코드 테이블
CREATE TABLE IF NOT EXISTS TB_DETAIL_CODE (
    GROUP_CODE VARCHAR(10) COMMENT '그룹코드',
    CODE VARCHAR(10) COMMENT '코드',
    DETAIL_CODE VARCHAR(10) COMMENT '상세코드',
    DETAIL_CODE_NAME VARCHAR(100) NOT NULL COMMENT '상세코드명',
    SORT_ORDER INT DEFAULT 0 COMMENT '정렬순서',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    MOD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (GROUP_CODE, CODE, DETAIL_CODE),
    CONSTRAINT FK_DETAIL_CODE FOREIGN KEY (GROUP_CODE, CODE) 
        REFERENCES TB_CODE(GROUP_CODE, CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='상세코드';

-- ========================================
-- 샘플 데이터 (이미지 참고)
-- ========================================

-- 그룹코드 샘플
INSERT INTO TB_GROUP_CODE (GROUP_CODE, GROUP_CODE_NAME, USE_YN) VALUES
('001', '성유종류', '사용'),
('002', '거래고객', '사용'),
('003', '', '사용'),
('004', '', '사용'),
('005', '', '사용')
ON DUPLICATE KEY UPDATE GROUP_CODE_NAME = VALUES(GROUP_CODE_NAME);

-- 코드 샘플
INSERT INTO TB_CODE (GROUP_CODE, CODE, CODE_NAME, SORT_ORDER, USE_YN) VALUES
('001', '1', '저장유통', 1, '사용'),
('001', '2', '처리유통', 2, '사용'),
('001', '3', '분리유통', 3, '사용'),
('001', '4', '단위구분유통', 4, '사용')
ON DUPLICATE KEY UPDATE CODE_NAME = VALUES(CODE_NAME);

-- 상세코드 샘플
INSERT INTO TB_DETAIL_CODE (GROUP_CODE, CODE, DETAIL_CODE, DETAIL_CODE_NAME, SORT_ORDER, USE_YN) VALUES
('001', '1', '1', '냉장', 1, '사용'),
('001', '2', '2', '냉동', 2, '사용')
ON DUPLICATE KEY UPDATE DETAIL_CODE_NAME = VALUES(DETAIL_CODE_NAME);

-- ========================================
-- 테이블 확인
-- ========================================
-- SHOW TABLES LIKE 'TB_%CODE';
-- DESC TB_GROUP_CODE;
-- DESC TB_CODE;
-- DESC TB_DETAIL_CODE;

-- SELECT * FROM TB_GROUP_CODE;
-- SELECT * FROM TB_CODE;
-- SELECT * FROM TB_DETAIL_CODE;
