-- 판매상품 테이블
CREATE TABLE TB_PRODUCT (
    PRODUCT_NO BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '상품번호',
    PRODUCT_NAME VARCHAR(200) NOT NULL COMMENT '상품명',
    SALE_PRICE INT DEFAULT 0 COMMENT '판매가격',
    COST_PRICE INT DEFAULT 0 COMMENT '원가',
    VAT_AMOUNT INT DEFAULT 0 COMMENT '부가세',
    SALE_START_DATE DATE COMMENT '판매시작일',
    SALE_END_DATE DATE COMMENT '판매종료일',
    DISPLAY_YN CHAR(1) DEFAULT 'N' COMMENT '노출여부(Y/N)',
    SELLER_ID BIGINT COMMENT '판매자ID',
    PRODUCT_SUMMARY VARCHAR(500) COMMENT '상품요약',
    MD_COMMENT VARCHAR(500) COMMENT 'MD 코멘트',
    DESCRIPTION TEXT COMMENT '상품상세설명',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    MOD_DT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    REG_ID VARCHAR(50) COMMENT '등록자',
    MOD_ID VARCHAR(50) COMMENT '수정자'
) COMMENT='판매상품';

-- 판매상품 구성 테이블 (구성상품 매핑)
CREATE TABLE TB_PRODUCT_COMPOSITION (
    COMPOSITION_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '구성ID',
    PRODUCT_NO BIGINT NOT NULL COMMENT '판매상품번호',
    BUNDLE_ID BIGINT NOT NULL COMMENT '구성상품번호',
    SORT_ORDER INT DEFAULT 0 COMMENT '정렬순서',
    FOREIGN KEY (PRODUCT_NO) REFERENCES TB_PRODUCT(PRODUCT_NO) ON DELETE CASCADE
) COMMENT='판매상품 구성';

-- 판매상품 이미지 테이블
CREATE TABLE TB_PRODUCT_IMAGE (
    IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '이미지ID',
    PRODUCT_NO BIGINT NOT NULL COMMENT '판매상품번호',
    IMAGE_TYPE VARCHAR(20) COMMENT '이미지유형(MAIN/DETAIL)',
    IMAGE_PATH VARCHAR(500) NOT NULL COMMENT '이미지경로',
    ORIGINAL_NAME VARCHAR(200) COMMENT '원본파일명',
    SORT_ORDER INT DEFAULT 0 COMMENT '정렬순서',
    FOREIGN KEY (PRODUCT_NO) REFERENCES TB_PRODUCT(PRODUCT_NO) ON DELETE CASCADE
) COMMENT='판매상품 이미지';
