-- =========================================================
-- 맛팜 Phase 3 현대화: DB 마이그레이션 DDL (MariaDB Optimized)
-- 작성일: 2026-03-27
-- 작성자: Release Manager (AI)
-- 목적: 기존 스키마(MariaDB)를 반영한 안정적 마이그레이션
-- =========================================================

-- 1. TB_SALES_PRODUCT (판매상품) 확장
-- 이미 DISCOUNT_AMT, VAT_YN이 존재한다면 무시하고 OP_TYPE만 추가
ALTER TABLE TB_SALES_PRODUCT ADD COLUMN IF NOT EXISTS DISCOUNT_AMT DECIMAL(18, 0) DEFAULT '0' AFTER cost_price;
ALTER TABLE TB_SALES_PRODUCT ADD COLUMN IF NOT EXISTS VAT_YN CHAR(1) DEFAULT 'N' AFTER DISCOUNT_AMT;
ALTER TABLE TB_SALES_PRODUCT ADD COLUMN IF NOT EXISTS OP_TYPE VARCHAR(20) DEFAULT 'LOCAL' AFTER del_yn;

-- 2. TB_ORDER / TB_ORDER_ITEM (주문/상세) 확장
-- MariaDB에 이미 vat_total_amt, pay_total_amt 등이 존재함을 확인. 
-- 누락된 OP_TYPE만 추가.
ALTER TABLE TB_ORDER ADD COLUMN IF NOT EXISTS OP_TYPE VARCHAR(20) DEFAULT 'LOCAL' AFTER addr2;
ALTER TABLE TB_ORDER_ITEM ADD COLUMN IF NOT EXISTS OP_TYPE VARCHAR(20) DEFAULT 'LOCAL' AFTER pay_amt;

-- 3. TB_MONEY_HISTORY (미트 머니 내역) - 신규
CREATE TABLE IF NOT EXISTS TB_MONEY_HISTORY (
    TRANS_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID VARCHAR(50) NOT NULL COMMENT '회원 PK',
    TRANS_TYPE VARCHAR(20) NOT NULL COMMENT 'DEDUCT:차감, CHARGE:충전, REFUND:반품',
    AMOUNT DECIMAL(18, 0) NOT NULL DEFAULT '0',
    BALANCE_BEFORE DECIMAL(18, 0) NOT NULL DEFAULT '0',
    BALANCE_AFTER DECIMAL(18, 0) NOT NULL DEFAULT '0',
    ORDER_ID VARCHAR(50) NULL COMMENT '관련 주문번호',
    REMARK VARCHAR(500) NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP(),
    INDEX IDX_MONEY_MEMBER (MEMBER_ID, REG_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='미트 머니 거래 이력';

-- 4. TB_SETTLEMENT (정산 데이터) - 신규
CREATE TABLE IF NOT EXISTS TB_SETTLEMENT (
    SETTLE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SETTLE_DT DATE NOT NULL COMMENT '정산 기준일',
    SELLER_MEMBER_ID VARCHAR(50) NOT NULL,
    TOTAL_SALES_AMT DECIMAL(18, 0) DEFAULT '0' COMMENT '총 판매액 (공급가)',
    TOTAL_VAT_AMT DECIMAL(18, 0) DEFAULT '0' COMMENT '총 부가세',
    TOTAL_FEE_AMT DECIMAL(18, 0) DEFAULT '0' COMMENT '수수료',
    SETTLE_PAY_AMT DECIMAL(18, 0) DEFAULT '0' COMMENT '최종 입금액',
    SETTLE_STATUS_CD VARCHAR(20) DEFAULT 'READY' COMMENT 'READY, PAID, FAIL',
    OP_TYPE VARCHAR(20) DEFAULT 'LOCAL',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE KEY UK_SETTLE_DATE (SETTLE_DT, SELLER_MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='판매자 정산 정합 데이터';

-- 5. 기본 데이터 보정
UPDATE TB_SALES_PRODUCT SET OP_TYPE = 'LOCAL' WHERE OP_TYPE IS NULL;
UPDATE TB_ORDER SET OP_TYPE = 'LOCAL' WHERE OP_TYPE IS NULL;
UPDATE TB_ORDER_ITEM SET OP_TYPE = 'LOCAL' WHERE OP_TYPE IS NULL;
