-- 1. Sample Buyer Member
INSERT INTO TB_MEMBER (
    MEMBER_ID, COMPANY_NAME, MEMBER_NAME, LOGIN_ID, PASSWORD, 
    MOBILE, EMAIL, STATUS_CD, MEMBER_TYPE_CD, 
    JOIN_DT, DEL_YN, PRIVACY_AGREE_YN, SMS_AGREE_YN, EMAIL_AGREE_YN
) VALUES (
    100, 'Handy CNG', 'Kim Gildong', 'handy', 'password',
    '010-1234-5678', 'handy@test.com', 'NORMAL', 'BUYER',
    NOW(), 'N', 'Y', 'Y', 'Y'
) ON DUPLICATE KEY UPDATE COMPANY_NAME='Handy CNG';

-- 2. Sample Sales Products (if needed)
INSERT INTO TB_SALES_PRODUCT (
    SALES_PROD_ID, SALES_PROD_NAME, SALES_PRICE, USE_YN, DEL_YN, REG_DT, REG_ID
) VALUES 
(100, '[Chilled] Boiled Pork Head Cutting 2kg', 20920, 'Y', 'N', NOW(), 'admin'),
(101, '[Frozen] Boiled Pork Rectum 5kg', 47610, 'Y', 'N', NOW(), 'admin')
ON DUPLICATE KEY UPDATE SALES_PROD_NAME=VALUES(SALES_PROD_NAME);

-- 3. Sample Orders
-- Order 1: ORDERED status
INSERT INTO TB_ORDER (
    ORDER_ID, ORDER_NO, ORDER_DT, 
    ORDER_STATUS_CD, DELIVERY_TYPE_CD, DELIVERY_STATUS_CD,
    GOODS_TOTAL_AMT, DELIVERY_TOTAL_AMT, DISCOUNT_TOTAL_AMT, VAT_TOTAL_AMT, PAY_TOTAL_AMT,
    BUYER_MEMBER_ID, 
    REGION_SIDO_CD, REGION_SIGUNGU_CD, 
    RECEIVER_NAME, RECEIVER_MOBILE, ZIP_CODE, RECEIVER_ADDR1, RECEIVER_ADDR2, DELIVERY_MEMO,
    DEL_YN, USE_YN, REG_ID, REG_DT
) VALUES (
    1000, '20241026-0001', '2024-10-26 11:22:33',
    'ORDERED', 'PARCEL', 'READY',
    230120, 4000, 34518, 2057, 199602,
    100,
    '41', '41590', 
    'Default Shipping', '010-5656-8878', '12314', 'Gyeonggi-do Hwaseong-si Dongtan-daero 677-12', 'Room 302', 'Please leave at the door.',
    'N', 'Y', 'admin', NOW()
) ON DUPLICATE KEY UPDATE ORDER_NO='20241026-0001';

-- Order 1 Items
INSERT INTO TB_ORDER_ITEM (
    ORDER_ITEM_ID, ORDER_ID, LINE_NO,
    SALES_PROD_ID, SALES_PROD_NAME, 
    SALES_PRICE, ORDER_QTY, TOTAL_AMT, 
    DEL_YN, REG_DT, REG_ID
) VALUES 
(2001, 1000, 1, 100, '[Chilled] Boiled Pork Head Cutting 2kg', 20920, 11, 230120, 'N', NOW(), 'admin'),
(2002, 1000, 2, 101, '[Frozen] Boiled Pork Rectum 5kg', 47610, 3, 142830, 'N', NOW(), 'admin')
ON DUPLICATE KEY UPDATE ORDER_ID=1000;

-- Order 2: PREPARING status
INSERT INTO TB_ORDER (
    ORDER_ID, ORDER_NO, ORDER_DT, 
    ORDER_STATUS_CD, DELIVERY_TYPE_CD, DELIVERY_STATUS_CD,
    GOODS_TOTAL_AMT, DELIVERY_TOTAL_AMT, DISCOUNT_TOTAL_AMT, VAT_TOTAL_AMT, PAY_TOTAL_AMT,
    BUYER_MEMBER_ID, 
    REGION_SIDO_CD, REGION_SIGUNGU_CD, 
    RECEIVER_NAME, RECEIVER_MOBILE, ZIP_CODE, RECEIVER_ADDR1, RECEIVER_ADDR2, DELIVERY_MEMO,
    DEL_YN, USE_YN, REG_ID, REG_DT
) VALUES (
    1001, '20241221-0002', NOW(),
    'PREPARING', 'DIRECT', 'PENDING',
    50000, 0, 0, 5000, 55000,
    100,
    '11', '11110', 
    'Direct Receiver', '010-9999-8888', '03030', 'Seoul Jongno-gu Sejong-daero', '123', 'Call before arrival',
    'N', 'Y', 'admin', NOW()
) ON DUPLICATE KEY UPDATE ORDER_NO='20241221-0002';

-- Order 2 Items
INSERT INTO TB_ORDER_ITEM (
    ORDER_ITEM_ID, ORDER_ID, LINE_NO,
    SALES_PROD_ID, SALES_PROD_NAME, 
    SALES_PRICE, ORDER_QTY, TOTAL_AMT, 
    DEL_YN, REG_DT, REG_ID
) VALUES 
(2003, 1001, 1, 101, '[Frozen] Boiled Pork Rectum 5kg', 47610, 1, 47610, 'N', NOW(), 'admin')
ON DUPLICATE KEY UPDATE ORDER_ID=1001;

-- 4. Sample Delivery Parcel for Order 1
INSERT INTO TB_ORDER_DELIVERY_PARCEL (
    ORDER_ID, COURIER_CD, TRACKING_NO, SHIPPED_DT,
    USE_YN, DEL_YN, REG_ID, REG_DT
) VALUES (
    1000, 'POST', '1234567890', NOW(),
    'Y', 'N', 'admin', NOW()
) ON DUPLICATE KEY UPDATE TRACKING_NO='1234567890';
